### ISSUE TITLE
Please add composer.json

### ISSUE THREAD

**Issue by novakivskiy** [PAYONE-GmbH/magento-1#14]
Will be very good if the module can be updated through the composer. Please add composer.json and modman file
Example:
{
    "name": "payone_gmbh/magento1",
    "type": "magento-module",
    "license": "GPL-3.0+",
    "description": "Payone Magento Extension",
    "keywords": ["payment", "Magento", "Payone"],
    "homepage": "http://www.payone.de",
    "authors": [
        {
            "name": "Payone",
            "email": "magento@payone.de"
        }
    ],
    "require": {
        "magento-hackathon/magento-composer-installer": "*"
    }
    
}

**Comment by fjbender** [comment]
Added ``composer.json`` and ``modman``, also submitted package to repositories.

**Comment by novakivskiy** [comment]
great, thanks

**Comment by TKlement** [comment]
Since you are already using the "magento-hackathon/magento-composer-installer", there is no need to use modman anymore.
The hackathon package is able to do everything you want to do with modman.

So please extend your composer.json with the mapping from modman. The modman file may stay to be compatible with older workflows. 
Currently we are remove every modman file from our repositories so we can slim down our tools.

`
{
  "name": "payone-gmbh/magento-1",
  "type": "magento-module",
  "license": "GPL-3.0+",
  "description": "Payone Magento Extension",
  "keywords": ["payment", "Magento", "Payone"],
  "homepage": "http://www.payone.de",
  "authors": [
    {
      "name": "Payone",
      "email": "magento@payone.de"
    }
  ],
  "support": {
    "email": "tech.support@payone.de"
  },
  "require": {
    "magento-hackathon/magento-composer-installer": "*"
  },
  "extra": {
    "map": [
      ["app/code/community/Payone/*","app/code/community/Payone/"],
      ["app/design/adminhtml/default/default/layout/payone/*","app/design/adminhtml/default/default/layout/payone/"],
      ["app/design/adminhtml/default/default/template/payone/*","app/design/adminhtml/default/default/template/payone/"],
      ["app/design/frontend/base/default/layout/payone/*","app/design/frontend/base/default/layout/payone/"],
      ["app/design/frontend/base/default/template/payone/*","app/design/frontend/base/default/template/payone/"],
      ["app/etc/modules/*","app/etc/modules/"],
      ["app/locale/de_DE/*.csv","app/locale/de_DE/"],
      ["app/locale/de_DE/template/email/payone/*","app/locale/de_DE/template/email/payone/"],
      ["app/locale/en_US/*.csv","app/locale/en_US/"],
      ["app/locale/en_US/template/email/payone/*","app/locale/en_US/template/email/payone/"],
      ["js/payone/","js/payone/"],
      ["js/prototype/windows/themes/payone/","js/prototype/windows/themes/payone/"],
      ["lib/Payone/*","lib/Payone/"],
      ["skin/adminhtml/default/default/payone/*","skin/adminhtml/default/default/payone/"],
      ["skin/frontend/base/default/payone/*","skin/frontend/base/default/payone/"]
    ]
  }
}
`

**Comment by tniebergall** [comment]
I think the modman file should not be removed, because there are also other implementations of composer and magento1, like the one from AOE.

**Comment by TKlement** [comment]
As I said the modman file can be used for projects using the modman variant.

**Comment by tniebergall** [comment]
Oh sorry my fault ;-)

**Comment by fjbender** [comment]
It's done.
