### ISSUE TITLE
Order on Peding status

### ISSUE THREAD

**Issue by gulshan-streammarket** [PAYONE-GmbH/magento-1#186]
Hello,

I can see some orders are in pending payment status for a long time.
I checked the Payone transaction and that show 
Last Txaction | REDIRECT

Why these orders not cancelled/closed automatically if payment not captured.
Is there any option in the extension that I don't know?

Thanks

**Comment by fjbender** [comment]
Hi,

This occurs most of the time when the customer didn't finish the transaction on e.g. PayPal's site. There's no way for us to really know, other than "no notification received from PayPal in a timeframe of xy hours". However, we don't want to go around and close any order, because there may be other problems delivering the notification to the shop.

Our support might help you identify if this is the case or if there is anything else wrong.

Best
