### ISSUE TITLE
CVC field is not validated !

### ISSUE THREAD

**Issue by luxmedia** [PAYONE-GmbH/magento-1#213]
We (and probably many others???) have a serious problem in a Magento 1.9.3.8 shop using Payone creditcard and CVC validation.

In the config settings for the paymenttype "creditcard", the "check CVC" option is set to "always" and the field is of course visible in the checkout. But customers can place an order without entering any CVC.

I talked with the Payone support about this issue and the technical support engineer was able to reproduce it in a test environment. 
So checkout is possible without CVC-validation, which is a huge problem for the shop-owner in terms of avoiding fake orders.

Please have a look into this.

Best regards
Volker Lux

**Comment by fjbender** [comment]
I see that this is a serious issue for some merchants. However, we do have the problem that several card types do not need a CVC check (as there is no CVC for those cards) and many merchants define individual card types for certain geographies (e.g. Dankort as a co-branded Visa in Denmark) where we can't enforce a CVC.

The easiest way would probably be to create a "simple CVC enforcement mode" where CVC for the default card types (Visa, Master, AMEX) is enforced. Merchants with individual card types would have to resort to modifying the script that generates our hosted iFrame configuration.

Which card types are needed in your case?

**Comment by luxmedia** [comment]
Thanks for your immediate reply.
In Magento we do not have any options for individual card types, just the default ones. In our case we are using the ones you noted: Visa, Master and AMEX. And we are using the hostedIframe solution, i forget to mention that, sorry.

Shouldn't it be default, that the CVC validation is configured properly/restrictive for the default card types and individual card types need individual CVC validation-rules? I think there should be some kind of CVC-validation override for these individual cardtypes instead of disabling CVC validation globally, shouldn't it?
And what is the field "Check CVC" in the Magento configuration for? It can be set to "no", "only_first" and "always", which makes me think if "always" is selected, the CVC is validated and if "no" is selected, it's not? Am i wrong about this? Is this setting option handled on the API-side at all?

**Comment by fjbender** [comment]
The "Check CVC" configuration option is misleadingly labeled. It only sets whether the CVC input field is displayed or not. Due to the nature of the hosted iFrame implementation on API side, it was not possible until recently to enforce a CVC at all. This has been changed by introducing the "length" parameter, which can be set for different card types, e.g. `{"A": 4, "V": 3, "M": 3, "J": 0}`. This, however, inhibits us to differentiate between a `V` card type meaning "regular Visa" and a `V` card type meaning "Dankort".

We'll come up with a solution here that hopefully handles all cases and gives enterprise merchants flexibility while enforcing CVC for regular cards.

**Comment by fjbender** [comment]
With #231 this is now possible.
