### ISSUE TITLE
PayPal Express Additional Address Line Not Adopted

### ISSUE THREAD

**Issue by sprankhub** [PAYONE-GmbH/magento-1#221]
If I use PayPal Express in the cart and have an "Adresszusatz" defined in my PayPal account, this "Adresszusatz" is not adopted and completely missing from the Magento address. This leads to many parcel returns for obvious reasons. Here are some screenshots, which show the issue:

1. Address in PayPal Express (see field "Adresszusatz")
![1-paypal-express-adresse-in-paypal](https://user-images.githubusercontent.com/930199/41839369-5e9ff49c-7863-11e8-8baf-9546fbcbb82d.png)

2. Address on PayPal Express review page (mind missing field "Adresszusatz")
![2-paypal-express-adresse-review-seite](https://user-images.githubusercontent.com/930199/41839376-6459679c-7863-11e8-9d2e-d01357ef7ba0.png)

3. Address in Magento Backend order page (mind missing field "Adresszusatz")
![3-paypal-express-adresse-magento-backend-1](https://user-images.githubusercontent.com/930199/41839380-672bfd18-7863-11e8-9626-680d1dc2ef4a.png)

4. Address in Magento Backend order address edit page (mind missing field "Adresszusatz")
![4-paypal-express-adresse-magento-backend-2](https://user-images.githubusercontent.com/930199/41839390-6aa26ee6-7863-11e8-9242-aadd0bcf4694.png)

**Comment by gndk** [comment]
I often have the same issue. Would be nice if this would be added to the company address field in magento.

**Comment by sprankhub** [comment]
By the way, I think this happens without PAYONE with the default Magento PayPal Express payment method as well. Anyway, I think you should fix this in your extension nevertheless.

Shopware seemed to have the same issue as well. See https://issues.shopware.com/issues/PT-8608 / https://github.com/shopwareLabs/SwagPaymentPaypal/pull/12.

**Comment by fjbender** [comment]
I guess this should be a no-brainer. The response already contains a parameter `add_paydata[shipping_addressaddition]`. It is handled by `\Payone_Core_Model_Service_Paypal_Express_Checkout::returnFromPaypal`. If you amend this [method](https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Model/Service/Paypal/Express/Checkout.php#L197) somewhere along the lines of

```php
                if ($item->getKey() == 'shipping_addressaddition') {
                    $billingAddress->setCompanyOrWhatever($item->getData()); // TODO
                    $shippingAddress->setCompanyOrWhatever($item->getData()); // TODO
                }
```

you should be able to set it to an adequate field (I haven't found anything resembling address addition, though).

**Comment by sprankhub** [comment]
Thanks for the insights @fjbender! Just to make sure that we do not misunderstand each other: My expectation would be that PAYONE solves this issue. Will you work on it soon?

**Comment by fjbender** [comment]
> Will you work on it soon?

I would, but I'm not sure where to put the address addition information. "Company" doesn't feel right as this might screw up B2B/B2C recognition, so I have no idea where to put it.

**Comment by gndk** [comment]
I forgot about street2 :-). That would be a better fit.

**Comment by fjbender** [comment]
We'll try and write it in street2 then. :)

**Comment by mvscheidt** [comment]
I'll just leave the comment here in the rare case anyone has the same issue and ends up here somehow:

I think the code in #225 causes the following combination to break - at least in our setup:

- Put Virtual Product in Cart (so you only have virtual products in the cart!)
- Use Paypal Express Checkout
- Have an "Additional" Address Line defined in your paypal address you intend to continue with

On the Review Page everything looks fine, but when you try to finish the checkout you don't get to the Success Page but instead get the following error

```
Fatal error: Uncaught Error: Call to a member function getStreet() on bool in /var/www/html/vendor/payone-gmbh/magento-1/app/code/community/Payone/Core/controllers/PexpressController.php:221 Stack trace: #0 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Payone_Core_PexpressController->placeOrderAction() #1 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('placeOrder') #2 /var/www/html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #3 /var/www/html/magento/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch() #4 /var/www/html/magento/app/Mage.php(701): Mage_Core_Model_App->run(Array) #5 /var/www/html/magento/index.php(83): Mage::run('', 'store') #6 {main} thrown in /var/www/html/vendor/payone-gmbh/magento-1/app/code/community/Payone/Core/controllers/PexpressController.php on line 221
```

The line in question is https://github.com/PAYONE-GmbH/magento-1/pull/225/files#diff-ccc980a2285ab11a8056bda6ef5bf3d1ea4fa86cc298eaed2d0c87293fd24f58R221

It should be enough to unset `PayoneShippingAddressaddition` (which is being set in here https://github.com/PAYONE-GmbH/magento-1/pull/225/files#diff-dd86842c41f0385ed882856ffd269ae1e54385018944bac19b7b4f56bac4ca5eR266 ) since the code checks if that property is set before calling the code that currently causes an issue.

----

There are also other issues with carts consisting only of Virtual Products, e.g. in `\Payone_Core_Block_Paypal_Express_Review::getShippingAddress` where `$street = $address->getStreet();` would have a similar issue since the shipping address is not defined (see line https://github.com/PAYONE-GmbH/magento-1/pull/225/files#diff-1436c75dd92772a4958cc3ec5cd3f709fe1e2bccbbc3fe9b4c35a7e679d9282dR93 )
