### ISSUE TITLE
Upgrade to latest version Parameter {cardexpiredate} faulty or missing] 

### ISSUE THREAD

**Issue by hardiklinksture** [PAYONE-GmbH/magento-1#227]
Hello,
Recently i update the Magento version 1.7.0.2 to 1.9.3.8 and Payone version : 3.4.9 to 4.1.7

When i pay using credit card it will show alert 
"[1077: Parameter {cardexpiredate} faulty or missing] - Verfallsdatum ungültig. Bitte überprüfen Sie die Angaben auf der Karte."

Can you please guide me.

Thanks

**Comment by fjbender** [comment]
Hi @hardiklinksture,

I'd recommend that you contact our Technical Support Team at tech.support@bspayone.com or +49 431 25968-500. They can help you with better, as they can scan our logs or offer screen sharing to see where exactly things go wrong.

If it turns out that there is a module bug, you're welcome to reopen the issue here.
