### ISSUE TITLE
Ratepay isn't shown anymore after update to 5.1.0

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/magento-1#469]
I have a mental block.

I updated from 4.4.1 to 5.1.0 and this line changed:
https://github.com/PAYONE-GmbH/magento-1/blob/master/app/code/community/Payone/Core/Block/Checkout/Onepage/Payment/Methods.php#L78

I don't understand WHY this line changed, but the effect is, that Ratepay is removed from the available methods. Can someone explain to me, what is happening here? And how do we get Ratepay back to show up in the checkout? :-)

Thanks in advance!

(I reviewed the changes to 5.2.0 an I don't think this fixes my problem - happy to get corrected!)

**Comment by hreinberger** [comment]
Hi @Schrank in https://github.com/PAYONE-GmbH/magento-1/commit/5332aab27d275c57fd6925c63b2f8c2eaa0d27c8 we introduced certain frontend validations that are checked. If the checkout doesn't match certain criteria, the payment methods are hidden. This prevents customers from using Ratepay who wouldn't be accepted by Ratepay anyway.
The validations are:

- zip code (5 digits in DE, 4 digits in CH and AT, 4-6 characters in NL)
- currency (EUR in DET, AT, NL, CHF in CH)
- minimum age of 18
- phone number (6 or more digits)
- bank account owner equals invoice recipient
- IBAN (conforms to SEPA requirements)
- shopping basket (in allowed min/max amount constraints)
- billing address and delivery address need to be equal

These are the basic validations Ratepay wants our plugin to perform in order to minimize declined orders and ensure good UX for customers.

So, maybe you're using invalid data in your checkout? The payment methods should show up when all criteria are met. If not, hit me up and we'll take a deeper look 🐞

**Comment by Schrank** [comment]
@hreinberger Thank you so much for a quick and super helpful answer (no irony included) <3

Ok to get this straigt: There is no way to use Ratepay without having the birthdate in the checkout, correct? The rest should be ok 😅

**Comment by hreinberger** [comment]
thanks ❤️ and yep, customers need to have a minimum age of 18 to pay via Ratepay.

**Comment by hreinberger** [comment]
PS: we ask for the customer's age ourselves in case you don't want them to fill this out in the address section of the checkout:
![grafik](https://user-images.githubusercontent.com/40197225/121009475-811a3e00-c794-11eb-9da1-e8acea233262.png)

**Comment by Schrank** [comment]
@hreinberger Uh, good thing! Because we currently use "Ratepay" and not "Ratepay Invoice" - will try!
